import mongoose from 'mongoose';

const FoundItemSchema = new mongoose.Schema({
  // --- AI-Generated Fields (auto-filled by Gemini Vision) ---
  item_name: {
    type: String,
    default: 'Unknown Item',
    trim: true,
    maxlength: 200,
  },
  description: {
    type: String,
    default: '',
    maxlength: 5000,
  },
  category: {
    type: String,
    default: 'Other',
    index: true,
  },

  // Full structured AI analysis output
  ai_analysis: {
    item_type: { type: String, default: '' },
    brand: { type: String, default: 'Unknown' },
    primary_color: { type: String, default: '' },
    secondary_color: { type: String, default: '' },
    material: { type: String, default: '' },
    condition: { type: String, default: '' },
    ocr_text_found: { type: String, default: '' },
    human_style_description: { type: String, default: '' },
    searchable_tags: { type: [String], default: [] },
  },

  // Secret questions generated by AI for ownership verification
  secret_verification_questions: {
    type: [String],
    default: [],
    select: false, // Never expose to public queries by default
  },

  // --- User-Provided Fields ---
  location: {
    type: String,
    default: 'Unknown',
    maxlength: 300,
    index: true,
  },
  image_url: {
    type: String,
    default: null,
  },
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  email: {
    type: String,
    required: true,
  },

  // --- Status Tracking ---
  status: {
    type: String,
    enum: ['active', 'claimed', 'returned'],
    default: 'active',
    index: true,
  },
  created_at: {
    type: Date,
    default: Date.now,
    index: true,
  },
});

// Compound index for Tier 1 filtering
FoundItemSchema.index({ status: 1, category: 1, location: 1, created_at: -1 });

export default mongoose.models.FoundItem || mongoose.model('FoundItem', FoundItemSchema);
